function Hd = filter_fmcw
%FILTER_FMCW 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 31-Oct-2022 15:53:36

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 4000;  % Sampling Frequency

Fstop1 = 37;              % First Stopband Frequency
Fpass1 = 38;              % First Passband Frequency
Fpass2 = 42;              % Second Passband Frequency
Fstop2 = 43;              % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
